<?php declare(strict_types=1);
/**
 * Created by PhpStorm.
 * User: jeroen
 * Date: 11-4-19
 * Time: 21:03
 */

/** @var $block \Elgentos\PrismicIO\Block\Template */

?>

<div class="prismicio-post">

    <?php echo $block->getChildHtml('prismicio.post.poster_image'); ?>

    <h6><?php echo $block->getChildHtml('prismicio.post.category'); ?></h6>
    <h1><?php echo $block->getChildHtml('prismicio.post.title'); ?></h1>

    <div>Date created: <?php echo $block->getChildHtml('prismicio.post.date.posted'); ?></div>
    <div>Last updated: <?php echo $block->getChildHtml('prismicio.post.date.updated'); ?></div>

    <div>
        <?php echo $block->getChildHtml('prismicio.post.body'); ?>
    </div>
</div>
